spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: ${DB_USERNAME:postgres}
    password: ${DB_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect